DEFAULT_LTACS = [
    "absurd $1",
    "absurd_hyp H",
    "Tactics.add_hypothesis H' p",
    "SetoidTactics.add_morphism_tactic",
    "admit",
    "assert_fails tac",
    "assert_succeeds tac",
    "assumption",
    "auto",
    "PeanoNat.Nat.auto'",
    "Tactics.autoinjection tac",
    "Tactics.autoinjections",
    "autounfold",
    "autounfold_one",
    "Tactics.bang",
    "bapply lemma todo",
    "PeanoNat.Nat.bitwise",
    "case_eq x",
    "PeanoNat.Nat.cases n",
    "casetype $1",
    "Init.class_apply c",
    "clear",
    "Tactics.clear_dup",
    "Tactics.clear_dups",
    "Tactics.clear_except hyp",
    "compare $1 $2",
    "compute",
    "congruence",
    "constr_eq $1 $2",
    "constr_eq_nounivs $1 $2",
    "constr_eq_strict $1 $2",
    "constructor",
    "contradict H",
    "contradiction",
    "convert_concl_no_check $1",
    "cut $1",
    "SetoidTactics.default_add_morphism_tactic",
    "destauto",
    "Bool.destr_bool",
    "destr_eq H",
    "destruct_all t",
    "Tactics.destruct_all_rec_calls",
    "Tactics.destruct_call f",
    "Tactics.destruct_call_as f l",
    "Tactics.destruct_call_as_in f l H",
    "Tactics.destruct_call_in f H",
    "Tactics.destruct_calls f",
    "Tactics.destruct_conjs",
    "Tactics.destruct_exists",
    "Tactics.destruct_nondep H",
    "Tactics.destruct_one_ex",
    "Tactics.destruct_one_pair",
    "Tactics.destruct_pairs",
    "SetoidTactics.destruct_proper",
    "Tactics.destruct_rec_calls",
    "dintuition",
    "discriminate",
    "Tactics.discriminates",
    "Tactics.do_nat n tac",
    "PeanoNat.Nat.double_induct n m",
    "dtauto",
    "eassumption",
    "easy",
    "easy'",
    "eauto",
    "econstructor",
    "ediscriminate",
    "eexact $1",
    "eexists",
    "einjection",
    "eleft",
    "elimtype $1",
    "Equivalence.equiv_simplify",
    "Equivalence.equiv_simplify_one",
    "Equivalence.equivify",
    "Equivalence.equivify_tac",
    "eright",
    "esimplify_eq",
    "esplit",
    "etransitivity",
    "exact_no_check $1",
    "exfalso",
    "exists",
    "f_equal",
    "CMorphisms.f_equiv",
    "Morphisms.f_equiv",
    "fail",
    "false_hyp H G",
    "find_equiv H",
    "finish_timing",
    "first _0",
    "firstorder",
    "fresh",
    "gintuition",
    "give_up",
    "has_evar $1",
    "hnf",
    "idtac",
    "PeanoNat.Nat.induct n",
    "NumPrelude.induction_maker n t",
    "induction_sigma2_in_using H rect",
    "induction_sigma_in_using H rect",
    "info_auto",
    "info_eauto",
    "info_trivial",
    "Tactics.inject H",
    "injection",
    "instantiate",
    "intro",
    "intros",
    "intuition",
    "inversion_sigma",
    "inversion_sigma_step",
    "invlist f",
    "is_cofix $1",
    "is_const $1",
    "is_constructor $1",
    "is_evar $1",
    "is_fix $1",
    "is_ground $1",
    "is_ind $1",
    "is_list_constr c",
    "is_proj $1",
    "is_var $1",
    "lapply $1",
    "PeanoNat.Nat.le_elim H",
    "left",
    "native_cast_no_check $1",
    "CMorphisms.normalizes",
    "Morphisms.normalizes",
    "not_evar $1",
    "now_show c",
    "PeanoNat.Nat.nzsimpl",
    "PeanoNat.Nat.nzsimpl'",
    "Tactics.on_application f tac T",
    "Tactics.on_call f tac",
    "Tactics.on_last_hyp tac",
    "optimize_heap",
    "PeanoNat.Nat.order",
    "PeanoNat.Nat.Private_Tac.order",
    "PeanoNat.Nat.Private_OrderTac.Tac.order",
    "PeanoNat.Nat.order'",
    "PeanoNat.Nat.Private_Tac.order_eq x y eqn",
    "PeanoNat.Nat.Private_OrderTac.Tac.order_eq x y eqn",
    "PeanoNat.Nat.Private_Tac.order_loop",
    "PeanoNat.Nat.Private_OrderTac.Tac.order_loop",
    "PeanoNat.Nat.order_nz",
    "PeanoNat.Nat.order_pos",
    "PeanoNat.Nat.Private_Tac.order_prepare",
    "PeanoNat.Nat.Private_OrderTac.Tac.order_prepare",
    "PeanoNat.Nat.Private_Tac.order_rewr x eqn",
    "PeanoNat.Nat.Private_OrderTac.Tac.order_rewr x eqn",
    "CMorphisms.partial_application_tactic",
    "Morphisms.partial_application_tactic",
    "Tactics.program_simpl",
    "Tactics.program_simplify",
    "Tactics.program_solve_wf",
    "CMorphisms.proper_normalization",
    "Morphisms.proper_normalization",
    "CMorphisms.proper_reflexive",
    "Morphisms.proper_reflexive",
    "CMorphisms.proper_subrelation",
    "Morphisms.proper_subrelation",
    "Tactics.rapply p",
    "red",
    "SetoidTactics.red_subst_eq_morphism concl",
    "CRelationClasses.reduce",
    "RelationClasses.reduce",
    "CRelationClasses.reduce_goal",
    "RelationClasses.reduce_goal",
    "CRelationClasses.reduce_hyp H",
    "RelationClasses.reduce_hyp H",
    "Tactics.refine_hyp c",
    "Setoid.refl_st",
    "reflexivity",
    "Tactics.replace_hyp H c",
    "restart_timer",
    "Tactics.reverse",
    "SetoidTactics.reverse_arrows x",
    "Tactics.revert_last",
    "Tactics.revert_until id",
    "revgoals",
    "right",
    "setoid_etransitivity",
    "setoid_reflexivity",
    "Equivalence.setoid_subst H",
    "Equivalence.setoid_subst_nofail",
    "setoid_symmetry",
    "SetoidTactics.setoidreplace H t",
    "SetoidTactics.setoidreplaceat H t occs",
    "SetoidTactics.setoidreplacein H H' t",
    "SetoidTactics.setoidreplaceinat H H' t occs",
    "shelve",
    "shelve_unifiable",
    "Tactics.show_goal",
    "Tactics.show_hyp id",
    "Tactics.show_hyps",
    "simpl",
    "CRelationClasses.simpl_crelation",
    "simpl_list",
    "simpl_proj_exist_in H",
    "RelationClasses.simpl_relation",
    "simplify_eq",
    "solve _0",
    "solve_constraints",
    "CRelationClasses.solve_crelation",
    "PeanoNat.Nat.solve_max",
    "PeanoNat.Nat.solve_min",
    "CMorphisms.solve_proper",
    "Morphisms.solve_proper",
    "RelationClasses.solve_relation",
    "CMorphisms.solve_respectful t",
    "Morphisms.solve_respectful t",
    "split",
    "ssimpl_list",
    "CMorphisms.subrelation_tac T U",
    "Morphisms.subrelation_tac T U",
    "subst",
    "PeanoNat.Nat.Private_Tac.subst_eqns",
    "PeanoNat.Nat.Private_OrderTac.Tac.subst_eqns",
    "Tactics.subst_no_fail",
    "Setoid.sym_st",
    "symmetry",
    "tauto",
    "time_constr tac",
    "Setoid.trans_st x",
    "transitivity $1",
    "trivial",
    "Init.unconvertible",
    "vm_cast_no_check $1",
    "PeanoNat.Nat.wrap l",
    "AddFvTail a l",
    "ApplyLemmaThen lemma expr kont",
    "ApplyLemmaThenAndCont lemma expr tac CONT_tac",
    "ZMicromega.Vars.Facts.MP.Dec.FSetDecideAuxiliary.E_eq_to_Logic_eq",
    "Field_tac.FFV Cst CstPow rO rI add mul sub opp div inv pow t fv",
    "Field_tac.FIELD FLD lH rl",
    "Field_tac.FIELD_SIMPL FLD lH rl",
    "Field_tac.FIELD_SIMPL_EQ FLD lH rl",
    "FV Cst CstPow rO rI add mul sub opp pow t fv",
    "FV_hypo_tac mkFV req lH",
    "Field_tac.Field_Scheme Simpl_tac n lemma FLD lH",
    "Field_tac.Field_norm_gen f n FLD lH rl",
    "Field_tac.Field_simplify",
    "Field_tac.Field_simplify_eq n FLD lH",
    "Field_tac.Field_simplify_gen f FLD lH rl",
    "Find_at a l",
    "Get_goal",
    "ZMicromega.Vars.Facts.MP.Dec.FSetDecideAuxiliary.Logic_eq_to_E_eq",
    "NArithRing.Ncst t",
    "OnEquation req",
    "OnEquationHyp req h",
    "OnMainSubgoal H ty",
    "Field_tac.PackField F req Cst_tac Pow_tac L1 L2 L3 L4 cond_ok pre post",
    "PackRing F req sth ext morph arth cst_tac pow_tac lemma1 lemma2 pre post",
    "ProveLemmaHyp lemma",
    "ProveLemmaHyps lemma",
    "Qfield.Qcst t",
    "Qfield.Qpow_tac t",
    "ReflexiveRewriteTactic FV_tac SYN_tac LEMMA_tac MAIN_tac fv terms",
    "Ring RNG lemma lH",
    "Ring_gen RNG lH rl",
    "Ring_norm_gen f RNG lemma lH rl",
    "Ring_simplify",
    "Ring_simplify_gen f RNG lH rl",
    "ArithRing.Ss_to_add f acc",
    "Zcst t",
    "Zpow_tac t",
    "Zpower_neg",
    "ZMicromega.Vars.Facts.MP.Dec.FSetDecideAuxiliary.abstract_elements",
    "Equality.abstract_eq_hyp H' p",
    "Equality.abstract_eq_proof",
    "Equality.abstract_eq_proofs",
    "abstract_ring_morphism set ext rspec",
    "ZMicromega.Vars.Facts.MP.Dec.FSetDecideAuxiliary.abstract_term t",
    "all f ls",
    "all_hyps f",
    "all_prop_hyps f",
    "ssreflect.apply",
    "ZMicromega.Vars.Facts.MP.Dec.FSetDecideAuxiliary.assert_decidability",
    "BinNat.N.auto'",
    "Equality.autoinjections_left",
    "Equality.autoinjections_right",
    "Reflect.bcongruence",
    "BinNat.N.bitwise",
    "BinInt.Z.bitwise",
    "Reflect.bleft",
    "Reflect.blia",
    "Equality.block_goal",
    "Equality.blocked t",
    "bnat_reflect",
    "ssrbool.bool_congr",
    "bool_cst t",
    "bool_reflect",
    "Zeven.boolify_even_odd",
    "Reflect.bright",
    "Reflect.bsplit",
    "ssreflect.case",
    "case_split",
    "case_split_concl",
    "case_split_concl_dep",
    "case_split_concl_on ind",
    "case_split_concl_on_dep ind",
    "case_split_concl_on_gen tac ind",
    "case_split_dep",
    "case_split_on ind",
    "case_split_on_dep ind",
    "case_split_on_gen tac ind",
    "case_splitting",
    "case_splitting_concl",
    "case_splitting_concl_dep",
    "case_splitting_concl_dep_nored",
    "case_splitting_concl_nored",
    "case_splitting_concl_on t",
    "case_splitting_concl_on_dep t",
    "case_splitting_concl_on_dep_nored t",
    "case_splitting_concl_on_nored t",
    "case_splitting_dep",
    "case_splitting_dep_nored",
    "case_splitting_nored",
    "case_splitting_on t",
    "case_splitting_on_dep t",
    "case_splitting_on_dep_nored t",
    "case_splitting_on_nored t",
    "BinNat.N.cases n",
    "cauto",
    "ZMicromega.Vars.Facts.MP.Dec.FSetDecideAuxiliary.change_to_E_t",
    "check_fv l",
    "check_is_list t",
    "Equality.clear_eq",
    "Equality.clear_eq_ctx",
    "Equality.clear_eq_proofs",
    "Equality.clear_eqs",
    "Equality.clear_refl_eq",
    "Equality.clear_refl_eqs",
    "Field_tac.coerce_to_almost_field set ext f",
    "coerce_to_almost_ring set ext rspec",
    "coerce_to_ring_ext ext",
    "compute_assertion eqn t' t",
    "congr_tac",
    "csimpl",
    "default_div_spec set reqe arth morph",
    "dep_destruct t",
    "Equality.depelim id",
    "Equality.depelim_nosimpl id",
    "Equality.depind id",
    "BinPos.Pos.destr_pggcdn IHn",
    "Equality.destruct_last",
    "BinInt.Z.destruct_max n",
    "BinInt.Z.destruct_sgn n",
    "destruct_sigma",
    "destruct_sigma_dep",
    "destruct_sigma_dep_in_goal",
    "destruct_sigma_in_goal",
    "ZMicromega.Vars.Facts.MP.Dec.FSetDecideAuxiliary.discard_nonFSet",
    "PreOmega.Z.div_mod_to_equations",
    "PreOmega.Z.div_mod_to_equations'",
    "PreOmega.Z.div_mod_to_equations_generalize x y",
    "PreOmega.Z.div_mod_to_equations_step",
    "Equality.do_case p",
    "Equality.do_depelim tac H",
    "Equality.do_depelim' rev tac H",
    "Equality.do_depelim_nosimpl tac H",
    "Equality.do_depind tac H",
    "Equality.do_ind p",
    "Equality.do_intros H",
    "ssreflect.done",
    "BinNat.N.double_induct n m",
    "dsolve",
    "eager_inverting",
    "eager_inverting_dep",
    "ecrush",
    "einst e",
    "einster e",
    "einstering",
    "ssreflect.elim",
    "Equality.elim_case p",
    "BinInt.elim_compare com1 com2",
    "Equality.elim_eq_rect",
    "Equality.elim_ind p",
    "Equality.elim_tac tac p",
    "Ndec.eqb2eq",
    "eqsolve",
    "esimp_hyps",
    "PreOmega.Z.euclidean_division_equations_cleanup",
    "ssreflect.exact",
    "ZMicromega.Vars.Facts.MP.expAdd",
    "exsimpl",
    "f_equal_tac",
    "fcrush",
    "Field_tac.field_elements set ext fspec pspec sspec dspec rk",
    "Field_tac.field_lemmas set ext inv_m fspec pspec sspec dspec rk",
    "firstorder_nolia_tac",
    "firstorder_tac",
    "ZMicromega.flatten_bool",
    "Field_tac.fold_field_cond req",
    "forward H",
    "forward_base tac e",
    "forward_nored H",
    "forwarding",
    "forwarding_nored",
    "ZMicromega.Vars.Facts.MP.Dec.fsetdec",
    "ZMicromega.Vars.Facts.MP.Dec.FSetDecideAuxiliary.fsetdec_body",
    "ZMicromega.Vars.Facts.MP.Dec.FSetDecideAuxiliary.fsetdec_rec",
    "fsolve",
    "full_einst e tac",
    "full_inst e tac",
    "fullunfold h",
    "fullunfold_all",
    "gen_add_push add Rsth Reqe ARth x",
    "gen_mul_push mul Rsth Reqe ARth x",
    "gen_reflexivity Rsth",
    "gen_ring_div set reqe arth morph dspec",
    "gen_ring_pow set arth pspec",
    "gen_ring_sign morph sspec",
    "gen_srewrite Rsth Reqe ARth",
    "gen_srewrite_sr Rsth Reqe ARth",
    "Field_tac.gen_with_field F c",
    "generalize_proofs",
    "generalize_proofs_in t",
    "generalize_proofs_in_goal",
    "generalize_proofs_in_hyp H",
    "generalizing",
    "get_Carrier RNG",
    "Field_tac.get_CondLemma FLD",
    "get_Eq RNG",
    "Field_tac.get_FEeval FLD",
    "Field_tac.get_FFV FLD",
    "Field_tac.get_FldCarrier FLD",
    "Field_tac.get_FldEq FLD",
    "Field_tac.get_FldPost FLD",
    "Field_tac.get_FldPre FLD",
    "Field_tac.get_Hyp_tac FLD",
    "Field_tac.get_L1 FLD",
    "Field_tac.get_L4 FLD",
    "Field_tac.get_Meta FLD",
    "get_MonPol lemma",
    "get_NormLemma RNG",
    "get_Post RNG",
    "get_Pre RNG",
    "Field_tac.get_RingFV FLD",
    "get_RingFV RNG",
    "get_RingHypTac RNG",
    "Field_tac.get_RingMeta FLD",
    "get_RingMeta RNG",
    "Field_tac.get_SimplifyEqLemma FLD",
    "Field_tac.get_SimplifyLemma FLD",
    "get_SimplifyLemma RNG",
    "Field_tac.get_term",
    "hammer",
    "hammer_features",
    "hammer_transl",
    "hauto",
    "hcrush",
    "hecrush",
    "hfcrush",
    "PreOmega.hide_Z_of_N t",
    "PreOmega.hide_Z_of_nat t",
    "PreOmega.hide_Zpos t",
    "impl_fwd e",
    "inList x lst",
    "BinNat.N.induct n",
    "Equality.inject_left H",
    "Equality.inject_right H",
    "ZMicromega.Vars.Facts.MP.Dec.FSetDecideAuxiliary.inst_FSet_hypotheses",
    "inster H",
    "inster0 e trace",
    "instering",
    "Equality.introduce p",
    "intros_until_atom",
    "ZMicromega.inv H",
    "inv_gen_phi rO rI cO cI t",
    "inv_gen_phiN rO rI add mul t",
    "inv_gen_phiNword rO rI add mul opp t",
    "inv_gen_phiZ rO rI add mul opp t",
    "inv_gen_phi_pos rI add mul t",
    "inv_morph_nothing t",
    "invert H",
    "invert_one_subgoal_gen tac H",
    "invert_one_subgoal_nored_gen tac H",
    "invert_sigma",
    "List.invlist f",
    "isNcst t",
    "isPcst t",
    "isProp t",
    "Qfield.isQcst t",
    "isZcst t",
    "isZpow_coef t",
    "Notations.is_ground $1",
    "Equality.is_ground_goal",
    "Equality.is_introduced H",
    "List.is_list_constr c",
    "isnatcst t",
    "isolve",
    "isolve_nolia",
    "isplit",
    "Env.jump_simpl",
    "lazy_list_fold_right fcons fnil l",
    "BinNat.N.le_elim H",
    "BinInt.Z.le_elim H",
    "leaf_solve",
    "leaf_solve_nolia",
    "lia",
    "lia_tac",
    "list_fold_left fcons fnil l",
    "list_fold_right fcons fnil l",
    "list_iter f l",
    "list_iter_gen seq f l",
    "lst_rev lst",
    "Field_tac.mkFieldexpr C Cst CstPow rO rI radd rmul rsub ropp rdiv rinv rpow t",
    "  fv",
    "mkHyp_tac C req Reify lH",
    "mkPolexpr C Cst CstPow rO rI radd rmul rsub ropp rpow t fv",
    "ssreflect.move",
    "myred",
    "Nnat.Nat2N.nat2N",
    "ArithRing.natcst t",
    "ArithRing.natpostring",
    "ArithRing.natprering",
    "nia",
    "noEvars t",
    "ZMicromega.Vars.Facts.MP.Dec.FSetDecideAuxiliary.no_logical_interdep",
    "notHyp P",
    "notInList x lst",
    "notProp t",
    "notTrivial P",
    "noteHyp P",
    "BinNat.N.nzsimpl",
    "BinInt.Z.nzsimpl",
    "BinNat.N.nzsimpl'",
    "BinInt.Z.nzsimpl'",
    "Omega.omega",
    "Equality.on_JMeq tac",
    "Equality.on_coerce_proof tac T",
    "Equality.on_coerce_proof_gl tac",
    "ZMicromega.Vars.Facts.MP.Dec.FSetLogicalFacts.or_not_l_iff P Q tac",
    "ZMicromega.Vars.Facts.MP.Dec.FSetLogicalFacts.or_not_l_iff_in P Q H tac",
    "ZMicromega.Vars.Facts.MP.Dec.FSetLogicalFacts.or_not_r_iff P Q tac",
    "ZMicromega.Vars.Facts.MP.Dec.FSetLogicalFacts.or_not_r_iff_in P Q H tac",
    "BinNat.N.order",
    "BinPos.Pos.order",
    "BinNat.N.Private_Tac.order",
    "BinPos.Pos.Private_Tac.order",
    "BinInt.Z.Private_Tac.order",
    "BinNat.N.Private_OrderTac.Tac.order",
    "BinInt.Z.Private_OrderTac.Tac.order",
    "BinInt.Z.order",
    "BinNat.N.order'",
    "BinInt.Z.order'",
    "BinNat.N.Private_Tac.order_eq x y eqn",
    "BinPos.Pos.Private_Tac.order_eq x y eqn",
    "BinInt.Z.Private_Tac.order_eq x y eqn",
    "BinNat.N.Private_OrderTac.Tac.order_eq x y eqn",
    "BinInt.Z.Private_OrderTac.Tac.order_eq x y eqn",
    "BinNat.N.Private_Tac.order_loop",
    "BinPos.Pos.Private_Tac.order_loop",
    "BinInt.Z.Private_Tac.order_loop",
    "BinNat.N.Private_OrderTac.Tac.order_loop",
    "BinInt.Z.Private_OrderTac.Tac.order_loop",
    "BinNat.N.order_nz",
    "BinInt.Z.order_nz",
    "BinNat.N.order_pos",
    "BinInt.Z.order_pos",
    "BinInt.Z.order_pos'",
    "BinNat.N.Private_Tac.order_prepare",
    "BinPos.Pos.Private_Tac.order_prepare",
    "BinInt.Z.Private_Tac.order_prepare",
    "BinNat.N.Private_OrderTac.Tac.order_prepare",
    "BinInt.Z.Private_OrderTac.Tac.order_prepare",
    "BinNat.N.Private_Tac.order_rewr x eqn",
    "BinPos.Pos.Private_Tac.order_rewr x eqn",
    "BinInt.Z.Private_Tac.order_rewr x eqn",
    "BinNat.N.Private_OrderTac.Tac.order_rewr x eqn",
    "BinInt.Z.Private_OrderTac.Tac.order_rewr x eqn",
    "ssreflect.over",
    "Equality.pi_eq_proof",
    "Equality.pi_eq_proof_hyp p",
    "Equality.pi_eq_proofs",
    "BinInt.Z.pos_or_neg a",
    "preprocess",
    "proofHyp_tac lH",
    "ssrbool.prop_congr",
    "Field_tac.prove_field_eqn ope FLD fv expr",
    "Field_tac.prove_rw ope x",
    "Field_tac.prove_with_field ope c",
    "qauto",
    "qblast",
    "qcrush",
    "qecrush",
    "qfcrush",
    "qforward H",
    "qforwarding",
    "qsimpl",
    "PreOmega.Z.quot_rem_to_equations",
    "PreOmega.Z.quot_rem_to_equations'",
    "PreOmega.Z.quot_rem_to_equations_generalize x y",
    "PreOmega.Z.quot_rem_to_equations_step",
    "rchange tp",
    "red_in_all",
    "red_in_concl",
    "Field_tac.reduce_field_expr ope kont FLD fv expr",
    "Field_tac.reduce_field_ope ope c",
    "relation_carrier req",
    "Field_tac.return_term x",
    "Equality.rewrite_refl_id",
    "ring_elements set ext rspec pspec sspec dspec rk",
    "ring_lemmas set ext rspec pspec sspec dspec rk",
    "Field_tac.ring_of_field f",
    "rsolve",
    "sapply e",
    "sauto",
    "sauto_actions",
    "sauto_tac",
    "sblast",
    "scongruence",
    "scrush",
    "sdepdestruct t",
    "sdepinvert H",
    "sdestr_gen dep H",
    "sdestruct t",
    "sdone_nolia_tac",
    "sdone_tac",
    "seasy",
    "sedepinvert H",
    "seinvert H",
    "seinvert_gen dep H",
    "ZMicromega.Vars.Facts.MP.Dec.F.set_iff",
    "ZMicromega.Vars.Facts.MP.FM.set_iff",
    "sfinal tac",
    "sfirstorder",
    "simp_hyp H",
    "simp_hyps",
    "Equality.simpl_JMeq",
    "Field_tac.simpl_PCond FLD",
    "Field_tac.simpl_PCond_BEURK FLD",
    "BinPos.Pos.simpl_compare",
    "BinPos.Pos.simpl_compare_in H",
    "Equality.simpl_dep_elim",
    "Equality.simpl_depind",
    "Equality.simpl_depind_l",
    "Equality.simpl_depind_r",
    "Equality.simpl_eq",
    "Equality.simpl_eqs",
    "Equality.simpl_existT",
    "Equality.simpl_existTs",
    "List.simpl_list",
    "QArith_base.simpl_mult",
    "Equality.simpl_one_JMeq",
    "Equality.simpl_one_dep_JMeq",
    "simpl_sigma",
    "simpl_solve",
    "simpl_solve_nolia",
    "Equality.simpl_uip",
    "simple_invert H",
    "simple_invert_dep H",
    "simple_invert_dep_nored H",
    "simple_invert_nored H",
    "simple_inverting",
    "simple_inverting_dep",
    "simple_inverting_dep_nored",
    "simple_inverting_gen tac",
    "simple_inverting_nored",
    "simple_splitting",
    "Equality.simplify_IH_hyps",
    "Equality.simplify_dep_elim",
    "Equality.simplify_eqs",
    "Equality.simplify_one_dep_elim",
    "Equality.simplify_one_dep_elim_term c",
    "sintro",
    "sintros",
    "sintuition",
    "sinv_gen dep H",
    "sinvert H",
    "sinvert_gen dep H",
    "BinNat.N.solve_max",
    "BinPos.Pos.solve_max",
    "BinInt.Z.solve_max",
    "BinNat.N.solve_min",
    "BinPos.Pos.solve_min",
    "BinInt.Z.solve_min",
    "srewrite H",
    "srewrite_in_concl H",
    "srewriting",
    "ssimpl",
    "List.ssimpl_list",
    "ssolve",
    "ssolve_gen tac",
    "ssolve_nolia",
    "ssreflect.ssrdone0",
    "ssrmatching.ssrpattern pattern",
    "ssubst",
    "strivial",
    "ZMicromega.Vars.Facts.MP.Dec.FSetDecideAuxiliary.substFSet",
    "BinNat.N.Private_Tac.subst_eqns",
    "BinPos.Pos.Private_Tac.subst_eqns",
    "BinInt.Z.Private_Tac.subst_eqns",
    "BinNat.N.Private_OrderTac.Tac.subst_eqns",
    "BinInt.Z.Private_OrderTac.Tac.subst_eqns",
    "Equality.subst_left_no_fail",
    "Equality.subst_right_no_fail",
    "subst_simpl",
    "sunfolding",
    "BinInt.Z.swap_greater",
    "Mult.tail_simpl",
    "PreOmega.Z.to_euclidean_division_equations",
    "tryrsolve",
    "trysolve",
    "trysolve_nolia",
    "un_done",
    "Equality.unblock_dep_elim",
    "Equality.unblock_goal",
    "unfold_local_defs",
    "ssreflect.unlock",
    "use_tac t",
    "vinst e",
    "with_hyps p f",
    "with_prop_hyps",
    "BinNat.N.wrap l",
    "xintro x",
    "zchange checker",
    "zchecker",
    "zchecker_abstract checker",
    "zchecker_ext",
    "zchecker_no_abstract checker",
    "Zdiv.zero_or_not a",
    "BinInt.Z.zero_pos_neg n",
    "PreOmega.zify",
    "PreOmega.zify_N",
    "PreOmega.zify_N_op",
    "PreOmega.zify_N_rel",
    "PreOmega.zify_binop t thm a b",
    "PreOmega.zify_nat",
    "PreOmega.zify_nat_op",
    "PreOmega.zify_nat_rel",
    "PreOmega.zify_op",
    "PreOmega.zify_op_1",
    "PreOmega.zify_positive",
    "PreOmega.zify_positive_op",
    "PreOmega.zify_positive_rel",
    "PreOmega.zify_unop t thm a",
    "PreOmega.zify_unop_core t thm a",
    "PreOmega.zify_unop_nored t thm a",
    "PreOmega.zify_unop_var_or_term t thm a",
    "BinInt.Z.zinduct n",
]
